[technote]
id = "SITCOMTN-145"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-145.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-145"
github_default_branch = "main"
date_created = 2024-11-04T14:28:41Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Marina"
name.family = "Pavlovic"
orcid = "https://orcid.org/0000-0001-5560-7051"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory"
internal_id = "RubinObsC"
address = "Avenida Juan Cisternas #1500, La Serena, Chile"

name.given = "Kshitija"
name.family = "Kelkar"
internal_id = "kelkark"
orcid = "https://orcid.org/0000-0002-8130-3593"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory"
internal_id = "RubinObsC"
address = "Avenida Juan Cisternas #1500, La Serena, Chile"

[[technote.authors]]
name.given = "Nacho"
name.family = "Sevilla"
internal_id = "sevillai"
affiliations = [{name = "CIEMAT", internal_id = "CIEMAT", address = "Av. Complutense 40 28040 Madrid Spain"}]


